# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arbitrum API documentation
name : Arbitrum
email: hello@arbitrum.com
description: > # this means to ignore newlines until "baseurl:"
  Image and video content moderation with transparent and detailed reporting
baseurl: "" # the subpath of your site, e.g. /blog
url: http://apidoc.arbitrum.com
#github_username:  arbitrum
#github_username:  arbitrum
google_analytics_key:
permalink: pretty

# Build settings
markdown: kramdown

# https://www.hacksparrow.com/how-to-disable-github-pages-default-rouge-code-highlighter.html
#karmdown:
#  input: GFM
#  hard_wrap: false
#  syntax_highlighter_opts:
#    disable: true

#theme: minima

collections:
  documentation:
    title: Documentation
    position: 1
  method:
    title: Methods
    position: 2
  callback:
    title: Callbacks
    position: 3

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - README.md.save
  - LICENCE
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: _documentation
    values: &anchor
      title:
      description:
      type:
      position:
      right_code:
  -
    scope:
      path: _method
    values:
      <<: *anchor
  -
    scope:
      path: _callback
    values:
      <<: *anchor

types:
  - get
  - put
  - delete
  - post
